[package]
name = "day21"
description = "Advent of Code 2020 - Day 21"
version = "0.1.0"
authors = ["Sergio de Carvalho <scarvalhojr@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
regex = "1.4"
lazy_static = "1.4"

