[package]
name = "day01"
description = "Advent of Code 2020 - Day 01"
version = "0.1.0"
authors = ["Sergio de Carvalho <scarvalhojr@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
common = "0.1"
